### PR TITLE
Extra-date-vars

### LINKED ISSUE #19: add created_date & last_modified_date as a variable
1. Move [firebase folder](https://github.com/fleetingnotes/fleeting-notes-flutter/tree/main/firebase) to its own repository call it `fleeting-notes-firebase` & make it a private repo
2. Update [get_all_notes](https://github.com/fleetingnotes/fleeting-notes-flutter/blob/main/firebase/functions/firestore.js#L68) function to include the `last_modified_timestamp` when returning the note value
3. Add {created_timestamp} & {last_modified_timestamp}, these will be in the [UTC format](https://www.w3.org/TR/NOTE-datetime#:~:text=Times%20are%20expressed%20in%20UTC,mm%22%20minutes%20ahead%20of%20UTC.) (with hours minutes & seconds) (note: don't delete datetime because people may still be using it in their template)
4. Add additional variables {created_date} and {last_modified_date} in the [getFilledTemplate function](https://github.com/fleetingnotes/fleeting-notes-obsidian/blob/master/src/main.ts#L248). These will be in the format: (e.g. format `2022-08-28`)
5. Update default metadata to:
```
---
# Metadata used for sync
id: "${id}"
title: "${title}"
source: "${source}"
created_date: "${created_date}"
last_modified_date: "${last_modified_date}"
---
${content}
```

Feedback:
Image

### PR DESCRIPTION
**Pull request by ransurf**
Changed long timestamp to simple YYYY-MM-DD for easy linking

Closes #19

### CODE REVIEW

**Review by ransurf — COMMENTED** [review]
also merge fn-firebase repo pr

merge code-reformat first to see less differences

**Comment by matthewwong525** [comment]
> also merge fn-firebase repo pr
> 
> merge code-reformat first to see less differences or else main.ts line 291 might throw errors

also you have write permissions now so you don't need to merge with a forked repo

**Comment by matthewwong525** [comment]
Also, i think you forgot to update the `DEFAULT_SETTINGS` in `settings.ts`

For reference: #19

**Comment by matthewwong525** [comment]
duplicate of #26

**Pull request closed without merging**
